//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameTable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Posts = new HashSet<Post>();
        }
    
        public int CategoryID { get; set; }
        public string Category1 { get; set; }
        public System.DateTime dateCreated { get; set; }
        public string categoryStarter { get; set; }
        public int Approval { get; set; }
    
        public virtual ICollection<Post> Posts { get; set; }
    }
}
